Test Slurm sets CPU frequency correctly
EPCCed/epcc-reframe pull request #47
Opened 2024-09-23 15:50 UTC by JPRichings

Two tests for Archer2:

1) Slurm job with no --cpu-freq argument has SLURM_CPU_FREQ_REQ=2000000

2) Slurm job with --cpu-freq=2250000 argument has SLURM_CPU_FREQ_REQ=2250000

2024-09-24 09:17 UTC, RuiApostolo commented
> I will update to appease the syntax/linting god (@RuiApostolo)

It's the single-quotes in lines 45 and 48.

2024-09-25 14:04 UTC, RuiApostolo requested changes

2024-09-25 14:04 UTC, RuiApostolo commented on tests/env/cpu_freq_check.py
> +    """Checks that CPU frequency is set to 2.25GHz by default"""
2.25GHz is not the default though, is it? I think the test and class descriptions should reflect that.

2024-09-25 14:14 UTC, JPRichings commented on tests/env/cpu_freq_check.py
> +    """Checks that CPU frequency is set to 2.25GHz by default"""
Thanks I caught a couple of other similar doc string errors and have updated them

2024-09-25 14:16 UTC, RuiApostolo approved these changes

2024-09-25 14:16 UTC, merged

2024-09-25 14:16 UTC, RuiApostolo commented
Thanks @JPRichings !