New tests to check pm counters are accessible and reporting
EPCCed/epcc-reframe pull request #49
Opened 2024-09-25 12:25 UTC by JPRichings

Test for pm counters added:

- Node Energy
- Node Power
- CPU Energy
- CPU Power
- Memory Energy
- Memory Power
- CPU0 temperature
- CPU1 temperature

2024-09-25 12:35 UTC, aturner-epcc requested changes
See note on reducing the number of PrgEnv for each test

2024-09-25 12:35 UTC, aturner-epcc commented on tests/env/counters_check.py
> +    valid_prog_environs = ["PrgEnv-cray", "PrgEnv-gnu", "PrgEnv-aocc"]
I think you should only choose a single PrgEnv otherwise each test will be run three times in an identical fashion

2024-09-25 12:47 UTC, RuiApostolo commented on tests/env/counters_check.py
> +    valid_prog_environs = ["PrgEnv-cray", "PrgEnv-gnu", "PrgEnv-aocc"]
Does it need `PrgEnv-cray` or could it be `Default`?
https://github.com/EPCCed/epcc-reframe/blob/518b1227148f8c47eebe8d7245fb05443a4831bd/configuration/archer2.py#L147C21-L147C22

2024-09-25 13:27 UTC, RuiApostolo commented on tests/env/counters_check.py
> +    valid_prog_environs = ["PrgEnv-cray", "PrgEnv-gnu", "PrgEnv-aocc"]
Ignore me, the `Default` environment is only valid for the `login` partition.

2024-09-26 15:36 UTC, JPRichings commented on tests/env/counters_check.py
> +    valid_prog_environs = ["PrgEnv-cray", "PrgEnv-gnu", "PrgEnv-aocc"]
@aturner-epcc happy for this to be resolved?

2024-09-26 15:40 UTC, aturner-epcc approved these changes
Thanks for the changes, merging....

2024-09-26 15:40 UTC, merged