20240925 xcompact3d capability
EPCCed/epcc-reframe pull request #51
Opened 2024-09-26 14:21 UTC by JPRichings

This pull request adds a few tests to the xcompact3d reframe test:

- Added xcompact3d_capability_ofi test designed to run at 4096 nodes. 
    - Not currently tested at scale but has environment and scripts recommended by Paul B. 
    - Target next Capability days to test.
- Added xcompact3d_capability_ucx test designed to run at 2048 nodes. 
    - Not currently tested at scale but has environment and scripts recommended by Paul B. 
    - Target next Capability days to test.
- Replaces xcompact3d_large test replacing the existing large test which runs on 1024 nodes
    - Not retested yet due to scale
- Added xcompact3d test run on 64 node
    - Tested on Archer2 CPU
- Added xcompact3d_small test run on 8 nodes     
    - Tested on Archer2 CPU
- Supporting input files also included in source directory
- All tests build xcompact3d from a source on github

2024-09-26 15:12 UTC, aturner-epcc requested changes
Thanks @JPRichings . Just a minor change to avoid causing issues with regular test runs.

2024-09-26 15:12 UTC, aturner-epcc commented on tests/apps/xcompact3d/xcompact3d_capability_ofi.py
> +    tags = {"performance", "largescale", "applications"}
Can we change the "largescale" tag to "hyperscale" here (or something else more appropriate? We use the "largescale" tag to run tests every week and we do not want to run the 4096 and 2048 sizes this often.

2024-09-26 15:12 UTC, aturner-epcc commented on tests/apps/xcompact3d/xcompact3d_capability_ucx.py
> +    tags = {"performance", "largescale", "applications"}
Same as comment above.

2024-09-26 15:14 UTC, JPRichings commented on tests/apps/xcompact3d/xcompact3d_capability_ofi.py
> +    tags = {"performance", "largescale", "applications"}
i have set up a new archer2 config for capability days so these shouldn't run normally. "valid_systems = ["archer2:compute-capability"]"

2024-09-26 15:14 UTC, JPRichings commented on tests/apps/xcompact3d/xcompact3d_capability_ofi.py
> +    tags = {"performance", "largescale", "applications"}
but yes happy to add a new tag also

2024-09-26 15:54 UTC, RuiApostolo reviewed
I think these many tests deserve a base class where they all inherit from - there's a lot of duplicated code, especially the sanity and performance functions.

2024-09-26 16:09 UTC, JPRichings commented
@RuiApostolo Yep your right I will rework as this is all common up to inputs

2025-11-05 09:53 UTC, aturner-epcc approved these changes
This looks good to me. Approving and merging

2025-11-05 09:53 UTC, merged